#!/bin/bash
#####-----------------------固定部分------------------------------#########
readonly rModuleName=module/auto/serialBuildByBranchName.module
readonly rRirPathProcessEnableId=/tmp/ProcessEnableIds
fileNamePID=$1
# 函数
if [ -f $rFilePathXbashModuleCommon ];then
    source  $rFilePathXbashModuleCommon
else
    echo -e "\033[1;31m    函数加载失败\n\
    toolsPath=$rFilePathXbashModuleCommon\n\
    \033[0m"
fi

ftFail(){
    local failInfo="${1}"
    ftEcho -e "${failInfo}，回车退出" && read -n1 ddd  && exit
}

#切换分支
filePathBranchList=$2
branchArray=($(cat $filePathBranchList))
[ -z "$branchArray" ] && ftFail 分支信息读取失败
branchName="${branchArray[$fileNamePID]}"
[ -z "$branchName" ]&& ftFail 分支名读取失败
git checkout "$branchName" || ftFail 分支切换失败

ftEcho -s "任务 ${fileNamePID} :开始执行"
#####----------------------自定义部分--------------------------#######



#####-----------------------固定部分------------------------------#########
cat ${rRirPathProcessEnableId}/${fileNamePID} > /dev/null
((fileNamePID=$fileNamePID+1))
(( ${#branchArray[@]}==$fileNamePID )) && /bin/rm -f $rRirPathProcessEnableId
exit