#! /bin/bash
#####---------------------流程函数---------------------------#########
ftTimeLong()
{
	 #时间少于1秒默认不显示操作耗时
	 #时间时分秒各单位不显示为零的结果
	time2=$(date +%s -d $(date +"%H:%M:%S"))
	time3=$(((time2-mTimeBackupStart)%60))
	time5=$(((time2-mTimeBackupStart)/3600))
	time4=$((((time2-mTimeBackupStart)-time5*3600)/60))
	if [ "$time5" -ne "0" ];
		then strS1=$time5时
		else strS1=""
	fi
	if [ "$time4" -ne "0" ];
		then strF1=$time4分
		else strF1=""
	fi
	if [ "$time3" -ne "0" ];
		then strM1=$time3秒
		else strM1=""
	fi
	if [ "$time3" -eq "0" ]&&[ "$time4" -eq "0" ] &&[ "$time5" -eq "0" ];
		then echo;echo;echo 1秒没到就结束了
		else echo 本技能耗时${strS1}${strF1}${strM1} ！
	fi
}

ftWhoAmI1()## #命令权限判定
{
	    for cmd in ${mCmdsPermissionBase[@]}
    	do
    	    if [ "$cmd" = "$mBaseShellParameter2" ];
    	    	then commandAuthority=base
    	    fi
    	done
        for cmd in ${mCmdsPermissionRoot[@]}
    	do
    	    if [ "$cmd" = "$mBaseShellParameter2" ];
    	    	then commandAuthority=root
    	    fi
    	done
    	if [ "$commandAuthority" = "" ];then
		   	if [[ $mBaseShellParameter2 =~ "v" ]];then
		   		echo \"Xrnsd extensions to bash\" V0.4.1.beta
			else
				ftReadMe;exit;
			fi
		fi
  }

ftWhoAmYou()
{
	if [ `whoami` != "root" ]&&[ "$commandAuthority" = "root" ]; then
		echo "当前用户权限过低，请转换为root 用户后重新运行" ;exit
	fi
	if [ `whoami` = "root" ]&&[ "$commandAuthority" = "base" ];  then
	    echo "转化普通用户后，再次尝试"; exit
	fi
}

ftMain()
{
		ftWhoAmI1
		while true; do
		case $mBaseShellParameter2 in
		    "help")  ftReadMe; break;;
		    *)  if [ `whoami` = "root" ]&&[ "$commandAuthority" = "root" ];then 
        		while true; do
				case $mBaseShellParameter2 in

				"os")						${mDirPathCmdTools}system_backup_restore.sh backup; break;;
				"restore")					${mDirPathCmdTools}system_backup_restore.sh restore; break;;
				*)							ftReadMe;exit;;

				esac
			    done
			fi
			if [ `whoami` != "root" ]&&[ "$commandAuthority" = "base" ]; then
				while true; do
				case $mBaseShellParameter2 in

				"clean_data_garbage")		ftCleanDataGarbage ; break;;
				"mtk_flashtool")			ftMtkFlashTool ; break;;
				"test")						${mDirPathCmdTools}test.sh; break;;
				"restartadb")				ftRestartadb1; break;;
				# "gjh") 					java -jar ${mDirNameHome}/tools/xls2values/androidi18nBuilder.jar; break;;
				"monkey")					ftKillPhoneAppByPackageName com.android.commands.monkey; break;;
				"systemui")					ftKillPhoneAppByPackageName com.android.systemui; break;;
				"launcher")					ftKillPhoneAppByPackageName com.android.launcher3; break;;
				*)							ftReadMe;exit;;

				esac
			    done
			fi
			ftWhoAmYou;break;;
		esac
	    done

    }

ftReadMe()
{

	cat<<EOF
    =========================================================================
    命令  --- 参数/命令说明
          |// 使用格式
          |
          |-- 参数1   ---------------- [参数权限] ----  参数说明
          |-- 参数2   ---------------- [参数权限] ----  参数说明
    =========================================================================
    xb  ----- 系统维护
          |// xb ×××××
          |
          |-- os       ---------------- [root] ------  备份系统
          |-- restore  ---------------- [root] ------  还原系统
    xc  ----- 常规自定义命令和扩展
          |// xc ×××××
          |                                                            
          |-- test   -------------------------------   shell测试
          |-- clean_data_garbage                       清空回收站   
          |-- restartadb  --------------------------   重启adb服务  
          |-- v ------------------------------------   自定义命令版本                                                 
          |-- help                                     查看自定义命令说明
          |-- gjh  ---------------------------------   生成国际化所需的xml文件
    xk  ----- 关闭手机指定进程
          |// xk ×××××
          |
          |-- monkey  -------------------------------  关闭monkey
          |-- systemui  -----------------------------  关闭systemui
    xl ----- 过滤 android 含有tag的所有等级的log
          |// xl tag

    //xg  ---- [无参] / 搜索文件里面的字符串
          |// xg 字符串

    xle ----- 过滤 android 含有tag的E级log
          |// xle tag

    xkd  ---- [无参] / 快速删除海量文件
          |// xkd 文件夹

    xbh ----- 根据标签过滤命令历史
          |// xbh 标签

    xp ----- 查看文件绝对路径
          |// xp 文件名

    xi  ---- [无参] / 快速初始化模块编译环境
    xr  ---- [无参] / 使.bashrc修改生效
    .   ---- [无参] / 进入上一级目录
    ..  ---- [无参] / 进入上两级目录
    xh  ---- [无参] / 浏览命令历史
    xd  ---- [无参] / mtk下载工具
    xu  ---- [无参] / 打开.bashrc
    .9  ---- [无参] / 打开.9工具
    xx  ---- [无参] / 休眠
    xs  ---- [无参] / 关机
    xss ---- [无参] / 重启
    
    ===============  临时命令 ===================
    xversion--[无参] / 查看软件版本
    xg6572 ----- 下载mtk6572的工程
          |// xg6572 分支名
EOF
}
