#!/bin/bash
#####-----------------------变量初始化------------------------------#########
local exceptionContent=
# 获取xbash所在目录 获取用户名,用户名对应密码
# 根据 config/example.config 新建 config/用户名.config，在.gitignore中插入记录
# 根据 module/bashrc/example.bashrc 新建 module/bashrc用户名.bashrc ，在.gitignore中插入记录

diaNameLocal="Xrnsd-extensions-to-bash"
dirPathLocal=$(cd "$(dirname "$0")";pwd)
isFail=

userNameLocal=$(who am i | awk '{print $1}'|sort -u)
if [ "${S/ /}" != "$S" ];then
    userNameLocal=$(whoami)
fi

userPasswdLocal=def_null
status=1
while [[ status -ne "0" ]]; do
    if [[ $userPasswdLocal != "def_null" ]]; then
        echo -e "\033[1;31m密码错误,请重新输入\033[0m";
    fi
    echo -en "请输入用户[$userNameLocal]对应的密码:"
    read -s userPasswdLocal
    echo $userPasswdLocal | sudo -p '' -S echo 2> /dev/null
    status=$?
done||exceptionContent=" 用户信息配置初始化失败"

#####-----------------------配置文件生成------------------------------#########
# git config
if [ -z `which git` ];then
        echo $userPasswdLocal | sudo -p '' -S apt-get install  git ||(echo git安装失败，请重新安装;return)
fi
filePathGitConfig=/home/${userNameLocal}/.gitconfig
if [ ! -f "$filePathGitConfig" ];then
    echo -en "请输入git用户名:"
    read gitName&&git config --global user.name "$gitName"
    echo -en "请输入git邮箱或联系方式:"
    read gitemailUrl&&git config --global user.email "$gitemailUrl"
    echo "已自动初始化gitconfig,需要修改的请查看$filePathGitConfig"
fi||exceptionContent="${exceptionContent}\n git配置初始化失败"

# config
        fileNameXbashConfigNew=${userNameLocal}.config
        dirPathXbashConfigBashrc=${dirPathLocal}/config/user
        filePathXbashConfigExample=${dirPathXbashConfigBashrc}/expmale.config
        filePathXbashConfigNew=${dirPathXbashConfigBashrc}/${fileNameXbashConfigNew}

        taguserPasswordBase="export\ userPassword="
        taguserPasswordNew="export\ userPassword=$userPasswdLocal"

        cp $filePathXbashConfigExample $filePathXbashConfigNew

        sed -i "s:$taguserPasswordBase:$taguserPasswordNew:g" $filePathXbashConfigNew||exceptionContent="${exceptionContent}\n xbash的用户信息配置初始化失败"

# bash
        filePathXbashModuleBashrcNew=${userNameLocal}/main.xbashrc
        if [[ ! -f "$filePathXbashModuleBashrcNew" ]]; then
            exceptionContent="${exceptionContent}\n xbash生效初始化失败"
        fi

#.inputrc
        fileNameXbashModuleBashrcInputrcBase=bash_input.module
        fileNameXbashModuleBashrcInputrcTraget=.inputrc
        filePathXbashModuleBashrcInputrc=${userNameLocal}/module/${fileNameXbashModuleBashrcInputrcTraget}
        if [[ ! -f "$filePathXbashModuleBashrcInputrc" ]]; then
            exceptionContent="${exceptionContent}\n xbash配置的命令历史适配逻辑初始化失败"
        fi

#自定义配置
#1 bashrc PS1 显示git branch 名字
#2 bashrc 历史 自动备份去重复
#3 

#####-----------------------配置生效------------------------------#########
dirPathHomeLocal=/home/${userNameLocal}
filePathHomeLocalConfig=${dirPathHomeLocal}/.bashrc

mv ${filePathHomeLocalConfig} ${filePathHomeLocalConfig}_backup
ln -s $filePathXbashModuleBashrcNew $filePathHomeLocalConfig

filePathHomeLocalConfigInputrc=${dirPathHomeLocal}/${fileNameXbashModuleBashrcInputrc}
mv ${filePathHomeLocalConfigInputrc} ${filePathHomeLocalConfigInputrc}_backup
ln -s $filePathXbashModuleBashrcInputrc $filePathHomeLocalConfigInputrc

#if [ ! -z `which git` ];then
    cd $dirPathLocal
    branchName="user_${userNameLocal}"
    git branch $branchName
    git checkout "$branchName"
    git add -A
    git commit -m "added config by $userNameLocal" >/dev/null||isFail=gitCommit
    echo "commit config by $userNameLocal"
#fi

#####------------------初始化结果信息显示-----------------------#########
if [[ -z "$exceptionContent" ]]; then
    echo "$diaNameLocal 初始化成功"
else
    echo -e "\033[1;31m${exceptionContent}\033[0m"
fi
