#!/bin/bash
#####-----------------------变量------------------------------#########
readonly rModuleName=test/base.sh
#####----------------------初始化demo环境--------------------------#######
# 函数
if [ -f $rFilePathXbashModuleCommon ];then
    source  $rFilePathXbashModuleCommon
else
    echo -e "\033[1;31m    函数加载失败\n\
    模块=$rModuleName\n\
    toolsPath=$rFilePathXbashModuleCommon\n\
    \033[0m"
fi

#####----------------------xbash 示例函数--------------------------#######
complete -W "-x -y -n" ftExample
ftExample()
{
    local ftEffect=函数模板
    local isEnable=true
    # debug用
    # trap 'printf "变量跟踪\e[33m %-7s \e[0m \e[31m %-30s \e[0m  \n" [$LINENO]: example1=$example1' DEBUG
    # trap 'printf "变量跟踪\e[33m %-7s \e[0m \e[31m %-30s \e[0m  \n" [$LINENO]: example1=$example1' ERR

    while true; do case "$1" in
    e | -e |--env) cat<<EOF
#===================[   ${ftEffect}   ]的使用环境说明=============
#
#    ${ftEffect}依赖包 example
#    请尝试使用 sudo apt-get install example 补全依赖
#=========================================================
EOF
      return;;
    h | H |-h | -H) cat<<EOF
#===================[   ${ftEffect}   ]的使用示例==============
#
#    ftExample 无参
#    ftExample [example]
#=========================================================
EOF
      return;;
    --df) cat<<EOF
#===================[   ${ftEffect}   ]的使用示例==============
#
#    ftExample已被禁用，请确认
#=========================================================
EOF
      return;;
    * ) break;;esac;done

    #可用校验
    if [ "$isEnable" != "true" ];then
        ftExample --df
        return
    fi

    #环境校验
    if [ -z `which example` ]||[ -z `which example` ];then
        ftExample -e
        return
    fi

    #参数解析,只支持短选项
    while getopts "x:yn" opt; do  case $opt in #参数x 需要跟数据,参数y或n不需要
       x) example1=$OPTARG
          ;;
        y) example2=yy
          ;;
        n) example2=nn
          ;;
    esac;done

    #耦合校验
    #local valCount=1
    local errorContent=
    #if (( $#!=$valCount ));then    errorContent="${errorContent}\\n[参数数量def=$valCount]valCount=$#" ; fi
    if [ -z "$example1" ];then    errorContent="${errorContent}\\n[示例1]example1=$example1" ; fi
    if [ -z "$example2" ];then    errorContent="${errorContent}\\n[示例2]example2=$example2" ; fi
    if [ ! -z "$errorContent" ];then
            ftEcho -ea "函数[${ftEffect}]的参数错误${errorContent}\\n请查看下面说明:"
            ftExample -h
            return
    fi
}

# ==============================================================================================================
