#!/bin/bash
#存放命令封装
#存放xbash扩展封装

alias ..="effect=进入父目录;cd .."
alias ...="effect=进入爷目录;cd ../.."
alias xcc='effect=进入原目录;cd $OLDPWD'

if [[ -n $(which cat) ]];then
    alias xbuildprop='effect=打印部分out下build.prop信息;[ -f "${ANDROID_PRODUCT_OUT}/system/build.prop" ] &&\
                      cat ${ANDROID_PRODUCT_OUT}/system/build.prop|grep "ro.product.model=" && \
                      cat ${ANDROID_PRODUCT_OUT}/system/build.prop|grep "ro.product.brand=" && \
                      cat ${ANDROID_PRODUCT_OUT}/system/build.prop|grep "ro.product.name=" && \
                      cat ${ANDROID_PRODUCT_OUT}/system/build.prop|grep "ro.product.device=" '
    alias xbh='effect=bash命令历史查询;cat $(ftBashHistory -p) |grep'
fi

if [[ -n $(which du) ]];then
    alias xdm='effect=查找最占用空间的20个目录;du -m --max-depth=2 | sort -nr | head -20 '
fi

if [[ -n $(which fuser) ]];then
     alias xkf='effect=解除文件或目录占用;fuser -m -k -i'
fi

if [[ -n $(which tr) ]];then
    alias xX='effect=字符串转大写;_xX(){  echo "$1" | tr '[a-z]' '[A-Z]' ;};_xX $1'
    alias Xx='effect=字符串转小写;_Xx(){  echo "$1" | tr '[A-Z]' '[a-z]' ;};_Xx $1'
fi

if [[ -n $(which todos) ]] && [[ -n $(which fromdos) ]];then
    alias unix2dos=todos
    alias dos2unix=fromdos
fi

if [[ -n $(which fdupes) ]];then
    alias xfr='effect=查找重复文件;fdupes -Sr'
fi

if [[ -n $(which pigz) ]];then
    alias xtgz='effect=快速生成压缩;ftPigz -c'
fi

if [[ -n $(which sensors) ]];then
    alias xcct="effect=查看cpu温度;ftMain -sc"
    alias xccct="effect=查看cpu各个核心温度;ftMain -scc"
fi

if [ -d "$ANDROID_SDK" ];then
    alias xp='effect=使用adb快速push[询问是否重启];ftAdbPush -f '
    alias xpa='effect=使用adb快速push[自动重启];ftAdbPush -a -f'
    alias xpn='effect=使用adb快速push[仅push];ftAdbPush -n -f'
    alias xpc='effect=使用adb快速push[新终端中执行,询问是否重启];ftAdbPush -c -f'
    alias xpca='effect=使用adb快速push[新终端中执行,自动重启];ftAdbPush -c -a -f'
    alias xpcn='effect=使用adb快速push[新终端中执行,仅push];ftAdbPush -c -n -f'
    alias xssd="effect=关闭设备;adb shell reboot"
    alias xsd="effect=关闭设备;adb shell reboot -p"
    alias xl='effect=过滤logcat;ftLogcatApplicationByTag'
    alias xle='effect=过滤错误的logcat;ftLogcatApplicationByTag -e'
    alias xlce='effect=过滤错误的logcat;adb logcat -c;ftLogcatApplicationByTag -e'
    alias xlp="effect=根据包名过滤logcat;ftLogcatApplicationByTag -p"
    alias xk='effect=干掉设备对应包名的进程;ftKillApplicationByPackageName'

    alias xpml='effect=干掉设备对应包名的进程;ftMtkLog -p /home/enjoy/log'

    alias .9='effect=.9图片制作工具;${ANDROID_SDK}/tools/draw9patch'
    alias xtp="effect=打印任务栈的栈顶信息;ftAdbContect && [ -n ${autoTestDeviceId} ] && adb -s ${autoTestDeviceId} shell dumpsys activity top"
    alias xds='effect=手机截图;adb shell screencap -p /sdcard/sc.png&&adb pull /sdcard/sc.png ~/download/'
    alias xdv='effect=手机录屏;adb shell screenrecord /sdcard/sv.mp4&&adb pull /sdcard/sv.mp4 ~/download/'

    alias xqdialer='effect=启动拨号盘;adb shell am start -n com.android.dialer/.DialtactsActivity'
    alias xqselect='effect=启动隐藏;adb shell am start -n com.mtk.select/com.mtk.select.SelectActivity'
    alias xqsetting='effect=启动设置;adb shell am start -n com.android.settings/com.android.settings.Settings'
    alias xqcamera='effect=启动Camera2;adb shell am start -n com.android.camera2/com.android.camera.CameraActivity'
    alias xqlauncher='effect=启动launcher;adb shell am start -n com.android.launcher3/com.android.launcher3.Launcher'
    alias xqfactorytest='effect=启动工厂测试;adb shell am start -n com.android.factorytest/com.android.factorytest.FTSamHomeActivity'
    alias xqmtklog='effect=启动MtkLog; adb shell am start -n com.mediatek.mtklogger/com.mediatek.mtklogger.MainActivity'
    alias xqengineermode='effect=启动工程模式; adb shell am start -n com.mediatek.engineermode/.EngineerMode'

    alias xgetevent='effect=打印输入设备事件节点清单; adb shell  -- getevent -p'

    [[ -f $rFilePathXbashDBBase ]] && packageNameList="$(ftIniGetValue $rFilePathXbashDBBase androidDevicePackages packageNameList)"
    complete -W "${packageNameList[@]} launcher systemui" xlp
    complete -W "${packageNameList[@]} launcher systemui 123456" xl
    complete -W "${packageNameList[@]} launcher systemui monkey" xk
fi

alias xc='effect=xbash主入口[旧];ftMain'
alias xb='effect=系统维护;ftMaintainSystem'
alias xr='effect=更新xbash配置;ftResetXbash'
alias xd='effect=MTK下载工具;ftMtkFlashTool'
alias xcg='effect=清空回收站;ftCleanGarbage -e -t'
alias xfind='effect=查找含特定字符串的文件;ftFind -s '
alias xfindOuts='effect=显示所有out备份;ftFindAospBuildOuts'
alias xhf='effect=xbash扩展说明查找;ftMain -h |grep -i '
alias xcb='effect=进入xbash目录;cd $dirPathHomeXbash'
alias xca='effect=快速切换到Aosp功能目录;ftCdAospDirectory '
alias xcd='effect=快速切换到不同Aosp项目;ftCdAospProject -n'
alias xcf='effect=进入xconfig目录;cd ${rDirPathUserHome}/xconfig'
alias xss='effect=无密码重启[默认10s];ftPowerManagement reboot'
alias xs='effect=无密码关机[默认10s];ftPowerManagement shutdown'
alias xrbcompare='effect=重新试用bcompare;rm -rf ~/.config/bcompare'
alias xcaf='effect=用文件管理器打开Aosp功能目录;ftCdAospDirectory -fm '
alias xcdf='effect=用文件管理器切换到不同Aosp项目;ftCdAospProject -fm '
alias xcdu='effect=快速更新Aosp项目列表配置;ftCdAospProject -u > /dev/null '

alias xas='effect=打开Android_studio;nohup ${rDirPathTools}/android-studio/bin/studio.sh & >/dev/null;rm nohup.out;exit'
alias xqmtklogview='effect=MTKlog分析工具;nohup /home/enjoy/tools/gat-linux-x86_64-3/modules/MediatekLogView/MediatekLogView \
& >/dev/null;rm nohup.out;exit'
alias xrbp='effect=删除out下面build.prop;rm -rf ${ANDROID_PRODUCT_OUT}/obj/ETC/system_build_prop_intermediates \
                                                                                 ${ANDROID_PRODUCT_OUT}/system/build.prop'
alias xep='effect=打开Eclipse;nohup ${rDirPathTools}/eclipse/eclipse & >/dev/null;exit'
alias xs2av='effect=android版本查询;ftIniGetValue $rFilePathXbashDBBase androidSDK2Verison'

if [ -f /usr/bin/gnome-session-quit ] ;then
     alias xsss='effect=注销系统;ftPowerManagement logout'
fi

if [[ -n $(which git) ]];then
    alias xgla='effect=查看本地所有分支历史;ftGitLogShell -a $2'
    alias xglbt='effect=查看本地仓库分支树;ftGitLogShell -at'
    alias xgl='effect=格式化显示20或xxx条git_log;ftGitLogShell -n 20'
    alias xglf='effect=格式化显示包含指定字符git_log;ftGitLogShell -n 100 |grep'
    alias xgat='effect=添加git的版本说明标签;ftGitTag -a '
    alias xgatt='effect=添加git的版本说明标签,使用模板;ftGitTag -t -a '
    alias xgmt='effect=添加git的修改说明标签;ftGitTag -m '
    alias xgbt='effect=添加git的分支说明标签;ftGitTag -b '
    alias xgdt='effect=删除git的TAG;ftGitTag -d '
    alias xgft='effect=git的TAG标签内容过滤;ftGitTagGrep -f '
    alias xglh='effect=显示xx条commit的hash值;ftGitLogShell -c "%h" -n '
    alias xgbrancha="effect=过滤git仓库所有分支;ftGitCheckoutBtanch -a -t"
    alias xgbranch="effect=过滤git仓库已经checkout分支;ftGitCheckoutBtanch -t"
    alias xgb="effect=过滤git仓库已经checkout分支;ftGitCheckoutBtanch -t"
    alias xgba="effect=过滤git仓库所有分支;ftGitCheckoutBtanch -a -t"
    alias xgrs="effect=回滚最新的commit;git reset --soft HEAD^"
fi

if [[ -n ftCdAospDirectory ]];then
    alias xcdlauncher='effect=快速进入launcher;ftCdAospDirectory app launcher'
    alias xcdsettings='effect=快速进入settings;ftCdAospDirectory app settings'
    alias xcddialer='effect=快速进入dialer;ftCdAospDirectory app dialer'
    alias xcdfactorytest='effect=快速进入factorytest;ftCdAospDirectory app factorytest'
    alias xcdsystemui='effect=快速进入systemui;ftCdAospDirectory frameworks base packages systemui'
    alias xcdsettingsprovider='effect=快速进入settingsprovider;ftCdAospDirectory frameworks base packages settingsprovider'
fi

if [[ -n $(which subl) ]];then
    alias xsubl='effect=使用sublime_text打开xbash和xconfig ; subl $rDirPathXbash ${rDirPathUserHome}/xconfig'
    alias xspwd='effect=使用sublime_text打开本目录;subl $(pwd)'
    alias xubpwm='effect=快速进入launcher;subl $(find frameworks/ -name "PhoneWindowManager.java")'
    alias xubsettings='effect=快速进入launcher;subl $(find frameworks/base/core -name "Settings.java")'
    alias xubl='effect=快速进入launcher;subl $(find frameworks/base/core -name "Settings.java")'
fi

if [[ -n $(which keytool) ]];then
    alias xkey='effect=查看秘钥文件的信息;keytool -exportcert -list -v -keystore '
fi

#命令选项快速适配
complete -F _ftMainVal xc
complete -W " -a --adb -j -h -s" xr
complete -F _cdAospDirectory xca
complete -F _cdAospDirectory xcaf
complete -W "--backup --restore --sd_finish -b -r -s" xb