#! /bin/bash
#####----------------------变量--------------------------#########

# 基本配置
export rXbashVersion="V0.1.2.0"
# 标记为脚本模式，此模式说明使用实现对应的封装命令
export XMODULE="script"

rNameUser=$(who am i | awk '{print $1}'|sort -u)
rNameUser=${rNameUser:-`whoami | awk '{print $1}'|sort -u`}
if [ "${S/ /}" != "$S" ];then
    rNameUser=$(whoami)
fi
export rNameUser

export rDirPathUserHome=/home/${rNameUser}
# home/xxxx
export rDirNameTools=tools
export rDirNameCmd=$dirNameXbash
# home/$rNameUser/xxxx
export rDirNameCmdConfig=config
export rDirNameCmdConfigData=base
export rDirNameCmdModule=module
# home/$rNameUser/cmds/modiule/test
export rDirNameCmdModuleTest=test
export DDP=$(cd `dirname $0`; pwd)
# home/$rNameUser/xxxx
export rDirPathCmds=${rDirPathUserHome}/${rDirNameCmd}
# home/$rNameUser/cmds/xxxx
export rDirPathCmdsConfig=${rDirPathCmds}/${rDirNameCmdConfig}
export rDirPathCmdsData=${rDirPathCmdsConfig}/${rDirNameCmdConfigData}
export rDirPathCmdsModule=${rDirPathCmds}/${rDirNameCmdModule}
export rDirPathCmdsModuleTest=${rDirPathCmdsModule}/${rDirNameCmdModuleTest}

# home/$rNameUser/cmds/modiule/test/xxxx
export rFileNameCmdModuleTestBase=base.sh
# home/$rNameUser/cmds/modiule/xxxx
export rFileNameCmdModuleTools=tools.sh
export rFileNameCmdModuleMS=maintain.sh

# home/$rNameUser/cmds/modiule/xxxx
export rFilePathCmdModuleTools=${rDirPathCmdsModule}/${rFileNameCmdModuleTools}


commandAuthority=null

# 非基本配置
export rDirPathTools=${rDirPathUserHome}/${rDirNameTools}

# ========设定只读=========

# 基本配置
readonly rXbashVersion
readonly rNameUser
readonly rDirPathUserHome

readonly rDirNameTools
readonly rDirNameCmd

readonly rDirNameCmdConfig
readonly rDirNameCmdData
readonly rDirNameCmdModule

readonly rDirNameCmdModuleTest

readonly rDirPathCmds
readonly rDirPathCmdsData
readonly rDirPathCmdsConfig
readonly rDirPathCmdsModule
readonly rDirPathCmdsModuleTest

readonly rFileNameCmdModuleTestBase
readonly rFileNameCmdModuleTools
readonly rFileNameCmdModuleMS

readonly rFilePathCmdModuleTools

readonly rCmdsPermissionRoot
readonly rCmdsPermissionBase
# 非基本配置
readonly rDirPathTools
