#! /bin/bash
#####----------------------变量--------------------------#########
export mUserPwd=123
export readonly mRoNameUser=`who | awk '{print $1}'|sort -u`
export readonly mRoDirPathUserHome=/home/${mRoNameUser}/

export readonly mRoDirNameLog=log
export readonly mRoDirNameCmd=cmds
export readonly mRoDirNameTools=tools

# 	dirPathCmdsDataValues=$(cd `dirname $0`; pwd)/
# export readonly mRoDirPathCmds=$(dirname $dirPathCmdsDataValues)
export readonly mRoDirPathCmds=${mRoDirPathUserHome}/${mRoDirNameCmd}
export readonly mRoDirNameCmdModule=module
export readonly mRoFileNameCmdModuleTest=test.sh
export readonly mRoFileNameCmdModuleTools=tools.sh
export readonly mRoFileNameCmdModuleCompile=compile.sh
export readonly mRoFileNameCmdModuleSbr=system_backup_restore.sh
export readonly mRoDirNameCmdData=data/

#外部参数
export readonly mRoBaseShellParameter1=$0
export readonly mRoBaseShellParameter2=$1
export readonly mRoBaseShellParameter3=$2

export readonly mRoTimeBackup=$(date -d "today" +"%m%d-%H:%M:%S")
export mTimingStart

export readonly mRoDirPathTools=${mRoDirPathUserHome}${mRoDirNameTools}
export readonly mRoDirPathCmdModule=${mRoDirPathUserHome}${mRoDirNameCmd}/${mRoDirNameCmdModule}

export readonly mRoCmdsPermissionRoot=(xb backup restore)
export readonly mRoCmdsPermissionBase=(restartadb help monkey systemui launcher mtk_flashtool gjh bootanim)

export readonly mRoIsDebug=false

export mCmdsModuleDataDevicesList=()
export mFilePathLog #=${mRoDirPathUserHome}${mRoDirNameLog}/${mRoBaseShellParameter2}.log
