#! /bin/bash
#####----------------------变量--------------------------#########
export readonly mRoDirNameCmd=cmds/
export readonly mRoDirNameCmdModule=module/
export readonly mRoFileNameCmdModuleTool=tools/
export readonly mRoFileNameCmdModuleData=data/
export readonly mRoDirNameLog=log/
export readonly mRoNameUser=`who | awk '{print $1}'|sort -u`
export mUserPwd=123

#脚本文件夹cmds放在home/××××/时，以下逻辑[mRoDirPathUserHome=用户主目录]有效
	dirName=${mRoDirNameCmd}
	dirPathCmdTools=$(cd `dirname $0`; pwd)/
export readonly mRoDirPathUserHome=${dirPathCmdTools/$mRoDirNameCmd/}

#外部参数
export readonly mRoBaseShellParameter1=$0
export readonly mRoBaseShellParameter2=$1
export readonly mRoBaseShellParameter3=$2

export readonly mRoTimeBackup=$(date -d "today" +"%m%d-%H:%M:%S")
export mTimingStart

export readonly mRoDirPathTools=${mRoDirPathUserHome}${mRoFileNameCmdModuleTool}
export readonly mRoDirPathCmdTools=${mRoDirPathUserHome}${mRoDirNameCmd}${mRoDirNameCmdModule}
export readonly mRoFilePathLog=${mRoDirPathUserHome}${mRoDirNameLog}${mRoBaseShellParameter2}___${mRoTimeBackup}.log

export readonly mRoCmdsPermissionRoot=(xb backup restore)
export readonly mRoCmdsPermissionBase=(restartadb help clean_data_garbage monkey systemui launcher mtk_flashtool)

export readonly mRoIsDebug=false
