#! /bin/bash
#----------------    bash config    ---------------------------
# 忽略特定命令
export HISTIGNORE="[   ]*:ls:ll:cd:vi:pwd:sync:exit:history*"
# 保存历史命令条数
export HISTSIZE=500
# 以追加的方式保存命令历史
shopt -s histappend
#自动去重备份bash历史记录
filePathBashHistory=${dirPathHome}/.bash_history 
filePathBashHistoryTemp=${filePathBashHistory}_temp
filePathBashHistoryArchive=${filePathBashHistory}_archive
filePathBashHistoryArchiveTemp=${filePathBashHistoryArchive}_temp
filePathGitBash=${dirPathHomeCmdConfig}/bashrc/git-completion.bash
#去重
sort -k2n $filePathBashHistory | awk '{if ($0!=line) print;line=$0}' >${filePathBashHistoryTemp}&&\
mv $filePathBashHistoryTemp $filePathBashHistory
#备份历史
let lineCountMax=HISTSIZE-1
lineCount=$(wc -l < $filePathBashHistory)
if (($lineCount > $lineCountMax)); then
    prune_lines=$(($lineCount - $lineCountMax))
    cat $filePathBashHistory >> $filePathBashHistoryArchive \
    && sort -k2n $filePathBashHistoryArchive | awk '{if ($0!=line) print;line=$0}' >${filePathBashHistoryArchiveTemp} \
    && mv $filePathBashHistoryArchiveTemp $filePathBashHistoryArchive \
    && > $filePathBashHistory
fi
alias ..="cd .."
alias ...="cd ../.."
alias xcc='cd $OLDPWD'
alias xr="source ~/.bashrc"


#----------------    xbash config  ---------------------------
fileNameXbashTragetConfigBase=config_base
filePathXbashTragetConfigBase=${dirPathHomeCmdConfig}/${fileNameXbashTragetConfigBase}
dirPathHomeCmdConfigBashrc=${dirPathHomeCmdConfig}/bashrc

if [ ! -z `which todos` ]||[ ! -z `which fromdos` ];then
    alias unix2dos=todos
    alias dos2unix=fromdos
fi

#全局变量
if [ -f $filePathXbashTragetConfigBase ];then
    #不重复添加config_base的只读设定
    if [ -z "$rNameUser" ];then
        source  $filePathXbashTragetConfigBase
    fi
    #标记为环境模式，此模式说明直接调用脚本实现
    export XMODULE="env"

    if [ -f ${rDirPathCmdsModule}/${rFileNameCmdModuleTools} ];then
        source  ${rDirPathCmdsModule}/${rFileNameCmdModuleTools}

        alias xle='export XCMD=xle;adb logcat "*:E"'
        #%Cblue%h%Creset %<(40,trunc)%s [%C(green)%<(21,trunc)%ai%x08%x08%Creset %Cred%an%Creset%C(yellow)%d%Creset]
        alias xgl='git log --date=short --pretty=format:"[%C(green)%<(21,trunc)%ai%x08%x08%Creset] %Cred%<(8,trunc)%an%Creset %Cblue%h%Creset %s" -15'
        alias xgll='git log --date=short --pretty=format:"[%C(green)%<(21,trunc)%ai%x08%x08%Creset] %Cred%<(8,trunc)%an%Creset %Cblue%h%Creset %s" -100'
        alias xb='export XCMD=xb;${dirPathHomeCmd}/main.sh'
        alias xk='ftKillPhoneAppByPackageName'
        alias xc='export XCMD=xc;${dirPathHomeCmd}/main.sh'
        alias xu='export XCMD=xu;gedit  ${dirPathHomeCmdConfigBashrc}/config_bashrc_base.gone\
                        ${dirPathHomeCmdConfigBashrc}/config_bashrc_base'
        alias xss='export XCMD=xss;${dirPathHomeCmd}/main.sh reboot'
        alias xs='export XCMD=xs;${dirPathHomeCmd}/main.sh shutdown'
        alias xd='export XCMD=xd;${dirPathHomeCmd}/main.sh mtk_flashtool'
        alias xbh='export XCMD=xbh;cat $filePathBashHistoryArchive $filePathBashHistory |grep $2'

        #命令选项快速适配
        complete -W "compile" xi
        complete -W "backup restore" xb
        complete -W "systemui monkey launcher" xk
        complete -W "restartadb help gjh test clean_data_garbage vvv bootanim pac -v -vvv -ft -ftall" xc

        # bash shell PS1 配置
         export PROMPT_COMMAND='\
         msg=$(history 1 | { read x y; echo $y; });\
         if [[ $msg =~ "git" ]];then
             ftSetBashPs1ByGitBranch
         fi'
        export PROMPT_COMMAND="ftSetBashPs1ByGitBranch;$PROMPT_COMMAND"
    else
        echo -e "\033[1;31mXbash函数加载失败[ToolsPath=${rDirPathCmdsModule}/${rFileNameCmdModuleTools}]\033[0m"
    fi
else
    echo -e "\033[1;31mXbash全局变量加载失败[filePathXbashTragetConfigBase=$filePathXbashTragetConfigBase]\033[0m"
fi
if [ -d "vendor/sprd" ];then
        alias xversion='cat packages/apps/Settings/src/com/android/settings/DeviceInfoSettings.java|grep "custom_build_version";\
                                cat packages/apps/Settings/src/com/android/settings/DeviceInfoSettings.java|grep "findPreference(KEY_BUILD_NUMBER).setSummary";\
                                cat packages/apps/ValidationTools/src/com/sprd/validationtools/itemstest/SystemVersionTest.java|grep -C 1 "platformVersion.setText(getString(R.string.build_number)"'
        alias xmodel='cat build/tools/buildinfo.sh|grep "ro.product.model=";\
                               cat build/tools/buildinfo.sh|grep "ro.product.brand=";\
                               cat build/tools/buildinfo.sh|grep "ro.product.name=";\
                               cat build/tools/buildinfo.sh|grep "ro.product.device=";\
                               cat device/sprd/scx20/sp7731c_1h10_32v4/sp7731c_1h10_32v4_oversea.mk |grep "product.model.num";\
                               cat frameworks/base/core/res/res/values/strings.xml |grep "wifi_tether_configure_ssid_default"'
        alias xcamera='cat device/sprd/scx20/sp7731c_1h10_32v4/BoardConfig.mk|grep "CAMERA_SUPPORT_SIZE :=";\
                                cat device/sprd/scx20/sp7731c_1h10_32v4/BoardConfig.mk|grep "LZ_CONFIG_CAMERA_TYPE :="'
fi